"""Public facade for temporal entity governance."""

from .contracts import (
    AliasReviewRequest,
    EntityDecisionRequest,
    EvidenceReference,
    MergeDecisionRequest,
    RelationAddRequest,
    RelationRetractRequest,
    SplitDecisionRequest,
)
from .errors import (
    EntityEvidenceReferenceRejected,
    EntityEvidenceVerificationBlocked,
    EntityGovernanceAccessDenied,
    EntityGovernanceConflict,
    EntityGovernanceError,
    EntityGovernanceNotFound,
    EntityGovernanceUnavailable,
)
from .evidence import (
    VERIFIED_EVIDENCE_KEYS,
    EvidenceSnapshotReader,
    validate_verified_evidence_metadata,
    verify_evidence_reference,
)
from .geography import (
    GEOGRAPHY_CATALOG_ID,
    GEOGRAPHY_CONTRACT_VERSION,
    GEOGRAPHY_DIMENSIONS_SCHEMA_VERSION,
    GEOGRAPHY_REASON_CODES,
    GEOGRAPHY_SCHEMA_VERSION,
    GeographicDimensionsInput,
    GeographicReferenceInput,
    GeographySemanticsCatalog,
    NormalizedGeographicDimensions,
    NormalizedGeographicReference,
    geography_semantics_catalog,
    normalize_geographic_dimensions,
    normalize_geographic_reference,
)
from .ledger import (
    EVENT_SCHEMA_VERSION,
    HISTORY_SCHEMA_VERSION,
    MAX_EVENTS,
    EntityGovernanceLedger,
)
from .seeds import (
    SEARCH_SEED_PROBES,
    SeedCatalogUnavailable,
    load_search_seed_entities,
)
from .service import (
    CATALOG_SCHEMA_VERSION,
    ENTITY_SCHEMA_VERSION,
    MUTATION_SCHEMA_VERSION,
    RELATION_SCHEMA_VERSION,
    STATUS_SCHEMA_VERSION,
    EntityGovernanceService,
    build_governance_projection,
)

__all__ = (
    "AliasReviewRequest",
    "CATALOG_SCHEMA_VERSION",
    "ENTITY_SCHEMA_VERSION",
    "EVENT_SCHEMA_VERSION",
    "EntityDecisionRequest",
    "EntityEvidenceReferenceRejected",
    "EntityEvidenceVerificationBlocked",
    "EntityGovernanceAccessDenied",
    "EntityGovernanceConflict",
    "EntityGovernanceError",
    "EntityGovernanceLedger",
    "EntityGovernanceNotFound",
    "EntityGovernanceService",
    "EntityGovernanceUnavailable",
    "EvidenceReference",
    "EvidenceSnapshotReader",
    "GEOGRAPHY_CATALOG_ID",
    "GEOGRAPHY_CONTRACT_VERSION",
    "GEOGRAPHY_DIMENSIONS_SCHEMA_VERSION",
    "GEOGRAPHY_REASON_CODES",
    "GEOGRAPHY_SCHEMA_VERSION",
    "GeographicDimensionsInput",
    "GeographicReferenceInput",
    "GeographySemanticsCatalog",
    "HISTORY_SCHEMA_VERSION",
    "MAX_EVENTS",
    "MUTATION_SCHEMA_VERSION",
    "MergeDecisionRequest",
    "NormalizedGeographicDimensions",
    "NormalizedGeographicReference",
    "RELATION_SCHEMA_VERSION",
    "RelationAddRequest",
    "RelationRetractRequest",
    "SEARCH_SEED_PROBES",
    "STATUS_SCHEMA_VERSION",
    "SeedCatalogUnavailable",
    "SplitDecisionRequest",
    "VERIFIED_EVIDENCE_KEYS",
    "build_governance_projection",
    "geography_semantics_catalog",
    "load_search_seed_entities",
    "normalize_geographic_dimensions",
    "normalize_geographic_reference",
    "validate_verified_evidence_metadata",
    "verify_evidence_reference",
)
