#!/usr/bin/env python3
"""Plan or apply an audited GlobeMind Web release promotion transaction."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Sequence

sys.dont_write_bytecode = True

from web_promotion import (  # noqa: E402
    PromotionApplyError,
    PromotionConfig,
    PromotionError,
    build_default_transaction,
    create_credential,
    sha256_bytes,
    write_credential,
)

PRODUCTION_PROJECT_DIR = Path("/root/data/globemind")
PRODUCTION_RELEASE_ROOT = Path("/root/data/releases/globemind")
PRODUCTION_RUNTIME_ROOT = Path("/root/data/python-runtimes/globemind-web")
PRODUCTION_CURRENT_LINK = PRODUCTION_RELEASE_ROOT / "current"
PRODUCTION_PREVIOUS_LINK = PRODUCTION_RELEASE_ROOT / "previous"
PRODUCTION_PID_FILE = Path("/root/data/web/pids/globemind_web_prod.pid")
PRODUCTION_DATABASE_PASSWORD_FILE = Path(
    "/root/data/secrets/globemind/web_runtime.password"
)
PRODUCTION_GENERATED_ASSET_ROOT = Path("/root/data/web/generated-assets")
PRODUCTION_AUDIT_ROOT = Path("/root/data/runtime/globemind/web/promotions")
PRODUCTION_ENVIRONMENT_FILES = (
    PRODUCTION_PROJECT_DIR / "backend/api/.env",
    PRODUCTION_PROJECT_DIR / "backend/agentic_rag/.env",
    PRODUCTION_PROJECT_DIR / ".env",
)


def _absolute(path: Path) -> Path:
    return Path(os.path.abspath(os.fspath(path)))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--request-id", required=True)
    parser.add_argument("--target-release", required=True, type=Path)
    parser.add_argument("--env-file", action="append", type=Path, required=True)
    parser.add_argument("--project-dir", type=Path, default=Path("/root/data/globemind"))
    parser.add_argument(
        "--release-root",
        type=Path,
        default=Path("/root/data/releases/globemind"),
    )
    parser.add_argument(
        "--runtime-root",
        type=Path,
        default=Path("/root/data/python-runtimes/globemind-web"),
    )
    parser.add_argument(
        "--current-link",
        type=Path,
        default=Path("/root/data/releases/globemind/current"),
    )
    parser.add_argument(
        "--previous-link",
        type=Path,
        default=Path("/root/data/releases/globemind/previous"),
    )
    parser.add_argument(
        "--controller",
        type=Path,
        default=Path("/root/data/globemind/deploy/start_web_prod.sh"),
    )
    parser.add_argument(
        "--verifier",
        type=Path,
        default=Path("/root/data/globemind/deploy/verify_release.py"),
    )
    parser.add_argument(
        "--verify-python",
        type=Path,
        default=Path("/usr/bin/python3"),
    )
    parser.add_argument(
        "--pid-file",
        type=Path,
        default=Path("/root/data/web/pids/globemind_web_prod.pid"),
    )
    parser.add_argument(
        "--database-password-file",
        type=Path,
        default=PRODUCTION_DATABASE_PASSWORD_FILE,
    )
    parser.add_argument(
        "--generated-asset-root",
        type=Path,
        default=Path("/root/data/web/generated-assets"),
    )
    parser.add_argument(
        "--audit-root",
        type=Path,
        default=Path("/root/data/runtime/globemind/web/promotions"),
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=18089)
    parser.add_argument("--web-workers", type=int, default=4)
    parser.add_argument("--warmup-rounds", type=int, default=12)
    parser.add_argument("--db-pool-size", type=int, default=3)
    parser.add_argument("--db-max-overflow", type=int, default=2)
    parser.add_argument("--db-pool-timeout", type=int, default=30)
    parser.add_argument("--stop-timeout", type=int, default=30)
    parser.add_argument("--controller-timeout", type=int, default=90)
    parser.add_argument("--health-timeout", type=int, default=60)
    parser.add_argument("--scheduler-max-heartbeat-age", type=int, default=180)
    parser.add_argument("--credential-ttl", type=int, default=180)
    parser.add_argument(
        "--credential-out",
        type=Path,
        help="Explicitly persist the dry-run credential for a later apply",
    )
    parser.add_argument("--credential", type=Path, help="Exact credential generated by dry-run")
    parser.add_argument("--credential-sha256", help="Operator-bound credential file digest")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--apply",
        action="store_true",
        help="Perform stop/link/start/health transaction; omitted means dry-run",
    )
    mode.add_argument(
        "--recover",
        action="store_true",
        help="Recover the exact interrupted transaction bound by the active journal",
    )
    return parser


def _config(args: argparse.Namespace) -> PromotionConfig:
    anchored = {
        "project-dir": (args.project_dir.resolve(strict=True), PRODUCTION_PROJECT_DIR.resolve()),
        "release-root": (args.release_root.resolve(strict=True), PRODUCTION_RELEASE_ROOT.resolve()),
        "runtime-root": (args.runtime_root.resolve(strict=True), PRODUCTION_RUNTIME_ROOT.resolve()),
        "current-link": (_absolute(args.current_link), PRODUCTION_CURRENT_LINK),
        "previous-link": (_absolute(args.previous_link), PRODUCTION_PREVIOUS_LINK),
        "pid-file": (_absolute(args.pid_file), PRODUCTION_PID_FILE),
        "database-password-file": (
            _absolute(args.database_password_file),
            PRODUCTION_DATABASE_PASSWORD_FILE,
        ),
        "generated-asset-root": (
            _absolute(args.generated_asset_root),
            PRODUCTION_GENERATED_ASSET_ROOT,
        ),
        "audit-root": (_absolute(args.audit_root), PRODUCTION_AUDIT_ROOT),
    }
    invalid = [name for name, (actual, expected) in anchored.items() if actual != expected]
    if invalid:
        raise PromotionError(f"production path anchors cannot be overridden: {sorted(invalid)}")
    environment_files = tuple(path.resolve(strict=True) for path in args.env_file)
    expected_environment = tuple(path.resolve(strict=True) for path in PRODUCTION_ENVIRONMENT_FILES)
    if environment_files != expected_environment:
        raise PromotionError("production environment files and order cannot be overridden")
    expected_controller = (PRODUCTION_PROJECT_DIR / "deploy/start_web_prod.sh").resolve(strict=True)
    expected_verifier = (PRODUCTION_PROJECT_DIR / "deploy/verify_release.py").resolve(strict=True)
    if args.controller.resolve(strict=True) != expected_controller:
        raise PromotionError("production controller path cannot be overridden")
    if args.verifier.resolve(strict=True) != expected_verifier:
        raise PromotionError("production verifier path cannot be overridden")
    if args.verify_python.resolve(strict=True) != Path("/usr/bin/python3").resolve(strict=True):
        raise PromotionError("production verification interpreter cannot be overridden")
    config = PromotionConfig(
        request_id=args.request_id,
        project_dir=args.project_dir.resolve(strict=True),
        release_root=args.release_root.resolve(strict=True),
        runtime_root=args.runtime_root.resolve(strict=True),
        target_release=args.target_release.resolve(strict=True),
        current_link=_absolute(args.current_link),
        previous_link=_absolute(args.previous_link),
        controller=args.controller.resolve(strict=True),
        verifier=args.verifier.resolve(strict=True),
        verify_python=args.verify_python.resolve(strict=True),
        pid_file=_absolute(args.pid_file),
        environment_files=environment_files,
        database_password_file=_absolute(args.database_password_file),
        generated_asset_root=_absolute(args.generated_asset_root),
        audit_root=_absolute(args.audit_root),
        host=args.host,
        port=args.port,
        web_workers=args.web_workers,
        warmup_rounds=args.warmup_rounds,
        db_pool_size=args.db_pool_size,
        db_max_overflow=args.db_max_overflow,
        db_pool_timeout=args.db_pool_timeout,
        stop_timeout_seconds=args.stop_timeout,
        controller_timeout_seconds=args.controller_timeout,
        health_timeout_seconds=args.health_timeout,
        scheduler_max_heartbeat_age_seconds=args.scheduler_max_heartbeat_age,
        credential_ttl_seconds=args.credential_ttl,
    )
    config.validate()
    return config


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    lifecycle_mode = args.apply or args.recover
    if lifecycle_mode:
        if args.credential is None or args.credential_sha256 is None:
            print(
                "--apply/--recover requires --credential and --credential-sha256",
                file=sys.stderr,
            )
            return 2
        if args.credential_out is not None:
            print("--credential-out is valid only in dry-run mode", file=sys.stderr)
            return 2
    elif args.credential is not None or args.credential_sha256 is not None:
        print(
            "--credential and --credential-sha256 require --apply or --recover",
            file=sys.stderr,
        )
        return 2

    try:
        config = _config(args)
        preflight, transaction = build_default_transaction(config)
        if args.apply:
            result = transaction.apply(
                _absolute(args.credential),
                args.credential_sha256,
            )
            print(json.dumps(result, ensure_ascii=True, sort_keys=True))
            return 0
        if args.recover:
            result = transaction.recover(
                _absolute(args.credential),
                args.credential_sha256,
            )
            print(json.dumps(result, ensure_ascii=True, sort_keys=True))
            return 0

        facts = preflight.capture(config)
        credential = create_credential(config, facts)
        raw = (
            json.dumps(
                credential,
                ensure_ascii=True,
                sort_keys=True,
                separators=(",", ":"),
                allow_nan=False,
            )
            + "\n"
        ).encode("utf-8")
        digest = sha256_bytes(raw)
        output = None
        if args.credential_out is not None:
            output = _absolute(args.credential_out)
            digest = write_credential(output, credential)
        print(
            json.dumps(
                {
                    "mode": "dry-run",
                    "status": "preflight-passed",
                    "request_id": config.request_id,
                    "target": facts["target"],
                    "rollback": facts["rollback"],
                    "credential_path": str(output) if output else None,
                    "credential_sha256": digest,
                    "expires_at": credential["expires_at"],
                    "apply_performed": False,
                },
                ensure_ascii=True,
                sort_keys=True,
            )
        )
        return 0
    except PromotionApplyError as exc:
        print(str(exc), file=sys.stderr)
        return 1 if exc.rollback_succeeded else 3
    except (OSError, PromotionError) as exc:
        print(f"promotion refused: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
