"""Public API for authentication, identity, and account contracts."""

from api.features.identity.application import authenticate_login
from api.features.identity.assurance import (
    ASSURANCE_SCHEMA_VERSION,
    IdentityAssuranceConflict,
    IdentityAssuranceStore,
    IdentityAssuranceUnavailable,
    IdentityFactorRejected,
    LoginChallengeRejected,
    configured_identity_assurance_store,
    hash_auth_version,
    hash_session_jti,
    totp_code,
    verify_totp,
)
from api.features.identity.contracts import (
    ApiConfigUpdateRequest,
    ChangePasswordRequest,
    FavoriteBatchOperation,
    FavoriteBatchRequest,
    FavoriteRemoveRequest,
    FavoriteToggleRequest,
    ForgotPasswordRequest,
    LoginMfaVerifyRequest,
    LoginRequest,
    MfaConfirmRequest,
    MfaDisableRequest,
    PrivacyDeletionRequestCreate,
    RegisterRequest,
    ResetPasswordRequest,
    SearchHistoryRequest,
    SessionRevokeRequest,
    UserProfileResponse,
    UserProfileUpdateRequest,
)
from api.features.identity.deletion_plan import (
    ACCOUNT_DELETION_PLAN_SCHEMA_VERSION,
    MAX_DELETION_PLAN_ITEMS,
    MAX_DELETION_PLAN_RESPONSE_BYTES,
    MAX_DELETION_PLAN_UNAVAILABLE_SCOPES,
    build_account_deletion_impact_plan,
)
from api.features.identity.health import probe_identity_health
from api.features.identity.privacy import (
    MAX_EXPORT_ADAPTER_BYTES,
    MAX_EXPORT_ADAPTER_TOTAL_BYTES,
    MAX_EXPORT_ADAPTERS,
    MAX_EXPORT_RELATIONAL_FIELD_BYTES,
    MAX_EXPORT_RELATIONAL_ITEM_BYTES,
    MAX_EXPORT_RELATIONAL_TOTAL_BYTES,
    MAX_PERSONAL_EXPORT_TOTAL_BYTES,
    PRIVACY_EXPORT_SCHEMA_VERSION,
    PRIVACY_REQUEST_SCHEMA_VERSION,
    PersonalDataExportAdapterBinding,
    PrivacyDeletionRequestStore,
    PrivacyRightsConflict,
    PrivacyRightsNotFound,
    PrivacyRightsUnavailable,
    build_personal_data_export,
)
from api.features.identity.provider_urls import (
    ProviderBaseUrlError,
    normalize_provider_base_url,
    provider_base_url_or_none,
)
from api.features.identity.repository import IdentityRepository

__all__ = (
    "ACCOUNT_DELETION_PLAN_SCHEMA_VERSION",
    "ASSURANCE_SCHEMA_VERSION",
    "ApiConfigUpdateRequest",
    "ChangePasswordRequest",
    "FavoriteBatchOperation",
    "FavoriteBatchRequest",
    "FavoriteRemoveRequest",
    "FavoriteToggleRequest",
    "ForgotPasswordRequest",
    "IdentityAssuranceConflict",
    "IdentityAssuranceStore",
    "IdentityAssuranceUnavailable",
    "IdentityFactorRejected",
    "IdentityRepository",
    "LoginChallengeRejected",
    "LoginMfaVerifyRequest",
    "LoginRequest",
    "MfaConfirmRequest",
    "MfaDisableRequest",
    "MAX_EXPORT_ADAPTERS",
    "MAX_EXPORT_ADAPTER_BYTES",
    "MAX_EXPORT_ADAPTER_TOTAL_BYTES",
    "MAX_EXPORT_RELATIONAL_FIELD_BYTES",
    "MAX_EXPORT_RELATIONAL_ITEM_BYTES",
    "MAX_EXPORT_RELATIONAL_TOTAL_BYTES",
    "MAX_PERSONAL_EXPORT_TOTAL_BYTES",
    "MAX_DELETION_PLAN_ITEMS",
    "MAX_DELETION_PLAN_RESPONSE_BYTES",
    "MAX_DELETION_PLAN_UNAVAILABLE_SCOPES",
    "PRIVACY_EXPORT_SCHEMA_VERSION",
    "PRIVACY_REQUEST_SCHEMA_VERSION",
    "PersonalDataExportAdapterBinding",
    "PrivacyDeletionRequestCreate",
    "PrivacyDeletionRequestStore",
    "PrivacyRightsConflict",
    "PrivacyRightsNotFound",
    "PrivacyRightsUnavailable",
    "ProviderBaseUrlError",
    "RegisterRequest",
    "ResetPasswordRequest",
    "SearchHistoryRequest",
    "SessionRevokeRequest",
    "UserProfileResponse",
    "UserProfileUpdateRequest",
    "authenticate_login",
    "build_account_deletion_impact_plan",
    "build_personal_data_export",
    "configured_identity_assurance_store",
    "hash_auth_version",
    "hash_session_jti",
    "normalize_provider_base_url",
    "probe_identity_health",
    "provider_base_url_or_none",
    "totp_code",
    "verify_totp",
)
