"""Public API for assistant interaction, schedules, and assurance."""

from api.features.assistant.application import (
    AssistantScheduleApplication,
    AssistantScheduleOperations,
    build_assistant_schedule_application,
)
from api.features.assistant.config import (
    AssistantScheduleSettings,
    assistant_schedule_runner_disabled,
    load_assistant_schedule_settings,
)
from api.features.assistant.contracts import (
    AssistantScheduleApplicationError,
    AssistantScheduleConflict,
    AssistantScheduleExecutionFailed,
    AssistantScheduleIdentity,
    AssistantScheduleIdentityError,
    AssistantScheduleNotFound,
    AssistantSchedulePayload,
)
from api.features.assistant.health import probe_assistant_health
from api.features.assistant.interactive_citations import (
    INTERACTIVE_CITATION_SCHEMA_VERSION,
    INTERACTIVE_SOURCE_SCHEMA_VERSION,
    MAX_INTERACTIVE_OUTPUT_LENGTH,
    InteractiveCitationError,
    InteractiveOutput,
    InteractiveSourceRecord,
    assure_interactive_output,
    bind_interactive_tool_result,
    finalize_interactive_output,
    interactive_source_records,
)
from api.features.assistant.privacy_export import (
    ASSISTANT_AUTOMATION_EXPORT_SCHEMA_VERSION,
    ASSISTANT_WORKSPACE_EXPORT_SCHEMA_VERSION,
    AssistantPrivacyExportReader,
    AssistantPrivacyExportUnavailable,
    configured_assistant_privacy_export_reader,
)
from api.features.assistant.prompt_registry import (
    PROMPT_RECEIPT_SCHEMA_VERSION,
    PROMPT_REGISTRY_SCHEMA_VERSION,
    PromptSpec,
    RegisteredPrompt,
    assistant_mode_prompt_id,
    interactive_prompt_bundle_receipt,
    registered_prompt_spec,
    render_registered_prompt,
)
from api.features.assistant.report_assurance import (
    ASSURANCE_SCHEMA_VERSION,
    ReportAssuranceError,
    ReportSourceRecord,
    assure_generated_report,
    assure_generated_structured_report,
    attach_write_time_draft_fingerprint,
    build_report_source_inventory,
    render_review_required_draft,
    source_inventory_prompt,
)
from api.features.assistant.structured_claim_evidence import (
    EXTERNAL_STRUCTURED_CLAIM_OBSERVATION_SCHEMA_VERSION,
    EXTERNAL_STRUCTURED_CLAIM_RECEIPT_SCHEMA_VERSION,
    ExternalStructuredClaimObservation,
    ExternalStructuredClaimRecord,
    ExternalStructuredClaimSourceArtifact,
    ExternalStructuredClaimVerificationReceipt,
    VerifiedExternalClaimSource,
    verify_external_structured_claim_observation,
)
from api.features.assistant.structured_claims import (
    STRUCTURED_CLAIM_SCHEMA_VERSION,
    GeneratedClaimEnvelope,
    GeneratedClaimInput,
    StructuredClaimError,
    StructuredClaimResult,
    finalize_structured_claim_output,
)

__all__ = (
    "AssistantScheduleApplication",
    "AssistantScheduleApplicationError",
    "AssistantScheduleConflict",
    "AssistantScheduleExecutionFailed",
    "AssistantScheduleIdentity",
    "AssistantScheduleIdentityError",
    "AssistantScheduleNotFound",
    "AssistantScheduleOperations",
    "AssistantSchedulePayload",
    "AssistantScheduleSettings",
    "INTERACTIVE_CITATION_SCHEMA_VERSION",
    "INTERACTIVE_SOURCE_SCHEMA_VERSION",
    "InteractiveCitationError",
    "InteractiveOutput",
    "InteractiveSourceRecord",
    "MAX_INTERACTIVE_OUTPUT_LENGTH",
    "PROMPT_RECEIPT_SCHEMA_VERSION",
    "PROMPT_REGISTRY_SCHEMA_VERSION",
    "PromptSpec",
    "RegisteredPrompt",
    "ASSISTANT_AUTOMATION_EXPORT_SCHEMA_VERSION",
    "ASSISTANT_WORKSPACE_EXPORT_SCHEMA_VERSION",
    "AssistantPrivacyExportReader",
    "AssistantPrivacyExportUnavailable",
    "ASSURANCE_SCHEMA_VERSION",
    "ReportAssuranceError",
    "ReportSourceRecord",
    "GeneratedClaimEnvelope",
    "GeneratedClaimInput",
    "EXTERNAL_STRUCTURED_CLAIM_OBSERVATION_SCHEMA_VERSION",
    "EXTERNAL_STRUCTURED_CLAIM_RECEIPT_SCHEMA_VERSION",
    "ExternalStructuredClaimObservation",
    "ExternalStructuredClaimRecord",
    "ExternalStructuredClaimSourceArtifact",
    "ExternalStructuredClaimVerificationReceipt",
    "STRUCTURED_CLAIM_SCHEMA_VERSION",
    "StructuredClaimError",
    "StructuredClaimResult",
    "VerifiedExternalClaimSource",
    "attach_write_time_draft_fingerprint",
    "assistant_mode_prompt_id",
    "assistant_schedule_runner_disabled",
    "assure_interactive_output",
    "assure_generated_report",
    "assure_generated_structured_report",
    "bind_interactive_tool_result",
    "build_report_source_inventory",
    "build_assistant_schedule_application",
    "configured_assistant_privacy_export_reader",
    "finalize_interactive_output",
    "finalize_structured_claim_output",
    "interactive_prompt_bundle_receipt",
    "interactive_source_records",
    "load_assistant_schedule_settings",
    "probe_assistant_health",
    "render_review_required_draft",
    "registered_prompt_spec",
    "render_registered_prompt",
    "source_inventory_prompt",
    "verify_external_structured_claim_observation",
)
